export interface PlayerStat {
  subject: string;
  A: number;
}

export interface Player {
  id: string;
  name: string;
  position: string;
  positionCategory: "Goalkeeper" | "Defender" | "Midfielder" | "Forward";
  number: string;
  age: number;
  ageGroup: "U-14" | "U-16" | "U-18";
  dob: string;
  gov: string;
  joined: number;
  height: string;
  weight: string;
  foot: "Right" | "Left" | "Both";
  bio: string;
  coachNotes: string;
  stats: PlayerStat[];
  images: string[];
  thumbnail: string;
}

// Stable Unsplash photo IDs (football/soccer themed) for thumbnails
const THUMB_QUERY = "?w=400&h=500&fit=crop&auto=format&q=70";
const thumb = (id: string) => `https://images.unsplash.com/photo-${id}${THUMB_QUERY}`;

// Shared gallery images (used in PlayerProfile gallery tab)
const sharedGallery = [
  "https://images.unsplash.com/photo-1674941136150-aa2f2df3e128?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHNvY2NlciUyMHBsYXllciUyMGFjdGlvbiUyMHNob3QlMjBpbnRlbnNlJTIwZ2FtZXxlbnwxfHx8fDE3NzEzMzYzODh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  "https://images.unsplash.com/photo-1612607700962-424524700884?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2NjZXIlMjBwbGF5ZXIlMjBydW5uaW5nfGVufDF8fHx8MTc3MTMzNjM5M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  "https://images.unsplash.com/photo-1650327987377-90bf6c9789fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2NjZXIlMjBiYWxsJTIwb24lMjBncmFzc3xlbnwxfHx8fDE3NzEzMzYzOTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
];

export const players: Player[] = [
  {
    id: "1",
    name: "Youssef Ibrahim",
    position: "Attacking Midfielder",
    positionCategory: "Midfielder",
    number: "10",
    age: 16,
    ageGroup: "U-16",
    dob: "12 May 2008",
    gov: "Cairo",
    joined: 2023,
    height: "178 cm",
    weight: "68 kg",
    foot: "Right",
    bio: "Youssef is a technically gifted playmaker with exceptional vision and dribbling ability. Scouted from a local tournament in Nasr City, he has quickly become the creative hub of the U-16 squad. His style is reminiscent of a young Mesut Özil, with a penchant for unlocking defenses with precise through balls.",
    coachNotes: "Has shown tremendous improvement in his defensive work rate this season. Needs to continue building physical strength to compete at the European level.",
    stats: [
      { subject: "Technique", A: 9 },
      { subject: "Speed", A: 7 },
      { subject: "Vision", A: 9.5 },
      { subject: "Strength", A: 6 },
      { subject: "Discipline", A: 8 },
      { subject: "Tactical", A: 8.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1574629810360-7efbbe195018"),
  },
  {
    id: "2",
    name: "Karim Mostafa",
    position: "Centre Back",
    positionCategory: "Defender",
    number: "4",
    age: 17,
    ageGroup: "U-18",
    dob: "03 March 2007",
    gov: "Alexandria",
    joined: 2022,
    height: "188 cm",
    weight: "78 kg",
    foot: "Right",
    bio: "Karim is a commanding presence at the back, combining aerial dominance with composed ball-playing skills. His leadership at U-18 level has been instrumental in the team's defensive record this season.",
    coachNotes: "Reads the game beautifully. Focus areas: improving recovery speed and one-on-one duels against pacy forwards.",
    stats: [
      { subject: "Technique", A: 7.5 },
      { subject: "Speed", A: 6.5 },
      { subject: "Vision", A: 8 },
      { subject: "Strength", A: 9 },
      { subject: "Discipline", A: 9 },
      { subject: "Tactical", A: 8.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1517466787929-bc90951d0974"),
  },
  {
    id: "3",
    name: "Mohamed Salah Ali",
    position: "Right Back",
    positionCategory: "Defender",
    number: "2",
    age: 15,
    ageGroup: "U-16",
    dob: "21 August 2009",
    gov: "Giza",
    joined: 2024,
    height: "173 cm",
    weight: "64 kg",
    foot: "Right",
    bio: "An energetic full-back blessed with relentless stamina and overlapping runs that consistently create danger in the final third. Mohamed combines defensive discipline with a flair for attacking.",
    coachNotes: "Crossing accuracy has improved sharply. Needs to time tackles better and avoid yellow cards in transition.",
    stats: [
      { subject: "Technique", A: 7 },
      { subject: "Speed", A: 9 },
      { subject: "Vision", A: 7 },
      { subject: "Strength", A: 7 },
      { subject: "Discipline", A: 7.5 },
      { subject: "Tactical", A: 7.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1517649763962-0c623066013b"),
  },
  {
    id: "4",
    name: "Ahmed Hassan",
    position: "Striker",
    positionCategory: "Forward",
    number: "9",
    age: 17,
    ageGroup: "U-18",
    dob: "10 January 2007",
    gov: "Aswan",
    joined: 2022,
    height: "182 cm",
    weight: "74 kg",
    foot: "Left",
    bio: "A clinical finisher with an instinct for arriving in the box at the right moment. Ahmed leads the U-18 scoring charts and is admired for his calm composure in front of goal.",
    coachNotes: "Hold-up play and link-up with midfield needs work. His off-the-ball movement is already at a professional level.",
    stats: [
      { subject: "Technique", A: 8 },
      { subject: "Speed", A: 8.5 },
      { subject: "Vision", A: 7.5 },
      { subject: "Strength", A: 8 },
      { subject: "Discipline", A: 7 },
      { subject: "Tactical", A: 8 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1543326727-cf6c39e8f84c"),
  },
  {
    id: "5",
    name: "Mahmoud Trezeguet",
    position: "Goalkeeper",
    positionCategory: "Goalkeeper",
    number: "1",
    age: 18,
    ageGroup: "U-18",
    dob: "30 November 2006",
    gov: "Luxor",
    joined: 2021,
    height: "192 cm",
    weight: "82 kg",
    foot: "Right",
    bio: "A towering shot-stopper whose reflexes and command of the area have earned him captaincy of the U-18 squad. Mahmoud's distribution has evolved into a key launching point for build-up play.",
    coachNotes: "Decision-making on crosses is elite. Continue refining footwork to become a true sweeper-keeper.",
    stats: [
      { subject: "Technique", A: 8 },
      { subject: "Speed", A: 6 },
      { subject: "Vision", A: 8.5 },
      { subject: "Strength", A: 9 },
      { subject: "Discipline", A: 9.5 },
      { subject: "Tactical", A: 9 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1551958219-acbc608c6377"),
  },
  {
    id: "6",
    name: "Omar Marmoush",
    position: "Left Midfielder",
    positionCategory: "Midfielder",
    number: "7",
    age: 16,
    ageGroup: "U-16",
    dob: "07 July 2008",
    gov: "Mansoura",
    joined: 2023,
    height: "176 cm",
    weight: "66 kg",
    foot: "Left",
    bio: "Direct, fearless, and quick to commit defenders, Omar is one of the most exciting wide players in the academy. His crosses and cut-inside shots have created countless chances this season.",
    coachNotes: "Decision-making in the final third is improving. Encourage him to vary the tempo of his runs.",
    stats: [
      { subject: "Technique", A: 8.5 },
      { subject: "Speed", A: 9 },
      { subject: "Vision", A: 7.5 },
      { subject: "Strength", A: 6.5 },
      { subject: "Discipline", A: 7 },
      { subject: "Tactical", A: 7.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1577223625816-7546f13df25d"),
  },
  {
    id: "7",
    name: "Mostafa Mohamed",
    position: "Defensive Midfielder",
    positionCategory: "Midfielder",
    number: "6",
    age: 17,
    ageGroup: "U-18",
    dob: "14 April 2007",
    gov: "Tanta",
    joined: 2022,
    height: "181 cm",
    weight: "72 kg",
    foot: "Right",
    bio: "The heartbeat of the U-18 midfield, Mostafa breaks up play with intelligent positioning and recycles possession with crisp, progressive passes.",
    coachNotes: "Tactical IQ is one of the highest in the squad. Work on adding box-to-box runs to his game.",
    stats: [
      { subject: "Technique", A: 8 },
      { subject: "Speed", A: 7 },
      { subject: "Vision", A: 8.5 },
      { subject: "Strength", A: 8 },
      { subject: "Discipline", A: 9 },
      { subject: "Tactical", A: 9 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1585567252041-1da849ae7d40"),
  },
  {
    id: "8",
    name: "Hamdi El-Shenawy",
    position: "Central Midfielder",
    positionCategory: "Midfielder",
    number: "8",
    age: 15,
    ageGroup: "U-16",
    dob: "19 September 2009",
    gov: "Sharm El-Sheikh",
    joined: 2024,
    height: "174 cm",
    weight: "65 kg",
    foot: "Both",
    bio: "A two-way midfielder with the rare gift of being equally effective with both feet. Hamdi dictates tempo and arrives late in the box for crucial goals.",
    coachNotes: "Stamina is exceptional for his age. Continue developing aerial play and long-range shooting.",
    stats: [
      { subject: "Technique", A: 8 },
      { subject: "Speed", A: 7.5 },
      { subject: "Vision", A: 8 },
      { subject: "Strength", A: 7 },
      { subject: "Discipline", A: 8.5 },
      { subject: "Tactical", A: 8 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1599058917212-d750089bc07e"),
  },
  {
    id: "9",
    name: "Akram Tawfik",
    position: "Right Winger",
    positionCategory: "Forward",
    number: "11",
    age: 16,
    ageGroup: "U-16",
    dob: "25 February 2009",
    gov: "Ismailia",
    joined: 2023,
    height: "175 cm",
    weight: "67 kg",
    foot: "Left",
    bio: "An inverted winger who thrives at cutting inside onto his stronger left foot. Akram combines acceleration with a sharp eye for goal.",
    coachNotes: "Decision-making between shooting and passing is the next step. Defensive tracking is much improved.",
    stats: [
      { subject: "Technique", A: 8.5 },
      { subject: "Speed", A: 9 },
      { subject: "Vision", A: 8 },
      { subject: "Strength", A: 6.5 },
      { subject: "Discipline", A: 7.5 },
      { subject: "Tactical", A: 7.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1526232761682-d26e03ac148e"),
  },
  {
    id: "10",
    name: "Mahmoud Kahraba",
    position: "Centre Back",
    positionCategory: "Defender",
    number: "5",
    age: 14,
    ageGroup: "U-14",
    dob: "06 December 2010",
    gov: "Port Said",
    joined: 2024,
    height: "180 cm",
    weight: "70 kg",
    foot: "Right",
    bio: "Despite being one of the youngest scholars, Mahmoud already physically dominates his age group. He's a ball-playing defender who steps into midfield to start attacks.",
    coachNotes: "Composure under pressure is rare for his age. Continue building tactical awareness in higher defensive lines.",
    stats: [
      { subject: "Technique", A: 7.5 },
      { subject: "Speed", A: 7 },
      { subject: "Vision", A: 8 },
      { subject: "Strength", A: 8.5 },
      { subject: "Discipline", A: 8 },
      { subject: "Tactical", A: 7.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1606925797300-0b35e9d1794e"),
  },
  {
    id: "11",
    name: "Saif El-Din",
    position: "Striker",
    positionCategory: "Forward",
    number: "19",
    age: 15,
    ageGroup: "U-16",
    dob: "11 June 2009",
    gov: "Suez",
    joined: 2023,
    height: "177 cm",
    weight: "69 kg",
    foot: "Right",
    bio: "A poacher in the truest sense, Saif lives off the shoulder of the last defender. His timing of runs behind the defensive line has produced a goal-every-other-game record.",
    coachNotes: "Link-up play in tight spaces is the focus this term. Finishing variety is already excellent.",
    stats: [
      { subject: "Technique", A: 8 },
      { subject: "Speed", A: 9 },
      { subject: "Vision", A: 7.5 },
      { subject: "Strength", A: 7.5 },
      { subject: "Discipline", A: 7.5 },
      { subject: "Tactical", A: 7.5 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1552667466-07770ae110d0"),
  },
  {
    id: "12",
    name: "Hossam Hassan",
    position: "Attacking Midfielder",
    positionCategory: "Midfielder",
    number: "21",
    age: 18,
    ageGroup: "U-18",
    dob: "02 October 2006",
    gov: "Cairo",
    joined: 2021,
    height: "179 cm",
    weight: "71 kg",
    foot: "Right",
    bio: "A senior scholar entering his final season, Hossam pulls the strings between the lines with elegant first touches and intelligent positional rotations.",
    coachNotes: "A model professional in training. Final development area is increasing his goal contributions from open play.",
    stats: [
      { subject: "Technique", A: 9 },
      { subject: "Speed", A: 7.5 },
      { subject: "Vision", A: 9 },
      { subject: "Strength", A: 7 },
      { subject: "Discipline", A: 9 },
      { subject: "Tactical", A: 9 },
    ],
    images: sharedGallery,
    thumbnail: thumb("1518091043644-c1d4457512c6"),
  },
];

export function getPlayerById(id: string | undefined): Player | undefined {
  if (!id) return undefined;
  return players.find((p) => p.id === id);
}
